In [14]:
import numpy as np

companies = np.loadtxt("financial_data.csv", delimiter=",", dtype=str)

companies

array([['Company', 'Quarter', 'Revenue', 'Profit', 'Expenses'],
       ['Company A', 'Q1', '25795', '6555', '19240'],
       ['Company A', 'Q2', '10860', '5385', '5475'],
       ['Company A', 'Q3', '48158', '6117', '42041'],
       ['Company A', 'Q4', '21284', '8396', '12888'],
       ['Company B', 'Q1', '16265', '6843', '9422'],
       ['Company B', 'Q2', '26850', '4904', '21946'],
       ['Company B', 'Q3', '47194', '9728', '37466'],
       ['Company B', 'Q4', '31962', '2474', '29488'],
       ['Company C', 'Q1', '26023', '3082', '22941'],
       ['Company C', 'Q2', '11685', '4558', '7127'],
       ['Company C', 'Q3', '10769', '9849', '920'],
       ['Company C', 'Q4', '12433', '4047', '8386'],
       ['Company D', 'Q1', '15311', '9643', '5668'],
       ['Company D', 'Q2', '47819', '4747', '43072'],
       ['Company D', 'Q3', '49188', '2975', '46213'],
       ['Company D', 'Q4', '27568', '3806', '23762']], dtype='<U9')

In [19]:
quarter = companies[3::3 + 1]

quarter

array([['Company A', 'Q3', '48158', '6117', '42041'],
       ['Company B', 'Q3', '47194', '9728', '37466'],
       ['Company C', 'Q3', '10769', '9849', '920'],
       ['Company D', 'Q3', '49188', '2975', '46213']], dtype='<U9')

In [62]:
filter_margin_values = np.array(quarter[:, 2:4])

filter_margin_values

array([[48158,  6117],
       [47194,  9728],
       [10769,  9849],
       [49188,  2975]])

In [77]:
profit_margin = filter_margin_values[:, 1].astype(int) / filter_margin_values[:, 0].astype(int)
profit_margin.reshape(-1, 1)


array([[0.12701939],
       [0.2061279 ],
       [0.9145696 ],
       [0.06048223]])

In [81]:
filter_expense_values = quarter[:, 4].astype(int) / quarter[:, 2].astype(int)

filter_expense_values.reshape(-1, 1)

array([[0.87298061],
       [0.7938721 ],
       [0.0854304 ],
       [0.93951777]])

In [84]:
all_profit_margin = companies[1:, 3].astype(int) / companies[1:, 2].astype(int)

all_profit_margin.reshape(-1, 1)

array([[0.25411902],
       [0.49585635],
       [0.12701939],
       [0.39447472],
       [0.42071934],
       [0.18264432],
       [0.2061279 ],
       [0.07740442],
       [0.11843369],
       [0.39007274],
       [0.9145696 ],
       [0.32550471],
       [0.62980863],
       [0.09927016],
       [0.06048223],
       [0.13805862]])

In [85]:
all_expense_values = companies[1:, 4].astype(int) / companies[1:, 2].astype(int)

all_expense_values.reshape(-1, 1)

array([[0.74588098],
       [0.50414365],
       [0.87298061],
       [0.60552528],
       [0.57928066],
       [0.81735568],
       [0.7938721 ],
       [0.92259558],
       [0.88156631],
       [0.60992726],
       [0.0854304 ],
       [0.67449529],
       [0.37019137],
       [0.90072984],
       [0.93951777],
       [0.86194138]])